### ISSUE TITLE
Homework 3 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-03-Kevin-diesel-1194#2]
Dear kevindiesel1194 -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

your score is **8.3/10**

I spread out the interpretation score, it would have been the same final score regardless. 

---

### Training and Data: `[8 / 10 points]`

- Reasonable choice for classification: `[6 / 6 points]`
- Narrative: `[2 / 4 points]`
- Feedback: [Insert feedback here.]

### Fitting classification models: `[19 / 22 points]`

  - Correct application: `[16 / 16]`
  - Narrative `[3 / 6]`
  - Feedback: [Insert feedback here.]

### Comparing models: `[7.5 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[2.5 / 5]`
  - Feedback: [Insert feedback here.]

### Applying chosen model: `[7.5 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[2.5 / 5]`
  - Feedback: [Insert feedback here.]

### Comparing decision boundaries: `[23 / 28 points]`

  - Correct application: `[18 / 18]`
  - Narrative: `[5 / 10]`
  - Feedback: [Insert feedback here.]

### Overall: `[18 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[1 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- **Feedback**: you don't use many commits and your messages are non-descriptive
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by Kevin-diesel-1194** [comment]
I recently became aware of the feedback regarding the narration in my submission, and I sincerely apologize for not checking the issue tab earlier. Upon reviewing the specific sections mentioned—fitting classification models, model comparison, and comparing decision boundaries—I realize that I may not have provided a sufficiently detailed narrative in some areas. I made an effort to discuss the code implementation for fitting models using the training data, including the "$finalmodel" for each model. Additionally, I touched upon the kappa and accuracy values of the best models in the model comparison section.
I acknowledge that my narrative in the comparison of decision boundaries section was not as comprehensive for certain models, and I genuinely appreciate your feedback in this regard. For models like SVM, LDA, and Naive Bayes, I aimed to provide a more thorough explanation. However, I understand that my narrative may have been mediocre for some models.
I totally agree with the assessment of the Applying chosen model section. I opted to focus on Random Forest and conveyed that it performed better without delving into a detailed explanation. Given these, It would be really great if I get credits for these narrations.

**Comment by Gchism94** [comment]
I will look again tomorrow. Based on your comment, I will likely give you 85/100 on the homework submission.

**Comment by Kevin-diesel-1194** [comment]
Thank you Dr. Greg.

**Comment by Gchism94** [comment]
You received 8.3/10, you had two points off for quality and quantity of your commits, but your overall score for this assignment is 18.3/20
